<?php


use think\migration\Seeder;

class MonitorMenusSeed extends Seeder
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        \catcher\Utils::importTreeData($this->getPermissions(), 'permissions', 'parent_id');
    }

    protected function getPermissions()
    {
       return array (
  0 => 
  array (
    'id' => 73,
    'permission_name' => '系统监控',
    'parent_id' => 0,
    'level' => '',
    'route' => '/monitor',
    'icon' => 'Camera',
    'module' => 'monitor',
    'permission_mark' => 'monitor',
    'component' => 'layout',
    'redirect' => '/monitor/crontab',
    'type' => 1,
    'is_link' => 0,
    'is_full' => 0,
    'is_hidden' => 0,
    'is_affix' => 0,
    'is_keepalive' => 1,
    'sort' => 1,
    'creator_id' => 1,
    'created_at' => 1600126383,
    'updated_at' => 1679668412,
    'deleted_at' => 0,
  ),
  1 => 
  array (
    'id' => 74,
    'permission_name' => '定时任务',
    'parent_id' => 73,
    'level' => '73',
    'route' => '/monitor/crontab',
    'icon' => 'ChatLineSquare',
    'module' => 'monitor',
    'permission_mark' => 'crontab',
    'component' => '/monitor/crontab/index',
    'redirect' => '',
    'type' => 1,
    'is_link' => 0,
    'is_full' => 0,
    'is_hidden' => 0,
    'is_affix' => 0,
    'is_keepalive' => 1,
    'sort' => 1,
    'creator_id' => 1,
    'created_at' => 1600126931,
    'updated_at' => 1679714985,
    'deleted_at' => 0,
  ),
  2 => 
  array (
    'id' => 75,
    'permission_name' => '列表',
    'parent_id' => 74,
    'level' => '73-74',
    'route' => '',
    'icon' => '',
    'module' => 'monitor',
    'permission_mark' => 'crontab@index',
    'component' => '',
    'redirect' => '',
    'type' => 2,
    'is_link' => 0,
    'is_full' => 0,
    'is_hidden' => 0,
    'is_affix' => 0,
    'is_keepalive' => 1,
    'sort' => 1,
    'creator_id' => 1,
    'created_at' => 1600127069,
    'updated_at' => 1679714985,
    'deleted_at' => 0,
  ),
  3 => 
  array (
    'id' => 76,
    'permission_name' => '保存',
    'parent_id' => 74,
    'level' => '73-74',
    'route' => '',
    'icon' => '',
    'module' => 'monitor',
    'permission_mark' => 'crontab@save',
    'component' => '',
    'redirect' => '',
    'type' => 2,
    'is_link' => 0,
    'is_full' => 0,
    'is_hidden' => 0,
    'is_affix' => 0,
    'is_keepalive' => 1,
    'sort' => 1,
    'creator_id' => 1,
    'created_at' => 1600127078,
    'updated_at' => 1679714985,
    'deleted_at' => 0,
  ),
  4 => 
  array (
    'id' => 77,
    'permission_name' => '更新',
    'parent_id' => 74,
    'level' => '73-74',
    'route' => '',
    'icon' => '',
    'module' => 'monitor',
    'permission_mark' => 'crontab@update',
    'component' => '',
    'redirect' => '',
    'type' => 2,
    'is_link' => 0,
    'is_full' => 0,
    'is_hidden' => 0,
    'is_affix' => 0,
    'is_keepalive' => 1,
    'sort' => 1,
    'creator_id' => 1,
    'created_at' => 1600127085,
    'updated_at' => 1679714985,
    'deleted_at' => 0,
  ),
  5 => 
  array (
    'id' => 78,
    'permission_name' => '删除',
    'parent_id' => 74,
    'level' => '73-74',
    'route' => '',
    'icon' => '',
    'module' => 'monitor',
    'permission_mark' => 'crontab@delete',
    'component' => '',
    'redirect' => '',
    'type' => 2,
    'is_link' => 0,
    'is_full' => 0,
    'is_hidden' => 0,
    'is_affix' => 0,
    'is_keepalive' => 1,
    'sort' => 1,
    'creator_id' => 1,
    'created_at' => 1600127091,
    'updated_at' => 1679714985,
    'deleted_at' => 0,
  ),
  6 => 
  array (
    'id' => 79,
    'permission_name' => '禁用/启用',
    'parent_id' => 74,
    'level' => '73-74',
    'route' => '',
    'icon' => '',
    'module' => 'monitor',
    'permission_mark' => 'crontab@disOrEnable',
    'component' => '',
    'redirect' => '',
    'type' => 2,
    'is_link' => 0,
    'is_full' => 0,
    'is_hidden' => 0,
    'is_affix' => 0,
    'is_keepalive' => 1,
    'sort' => 1,
    'creator_id' => 1,
    'created_at' => 1600129279,
    'updated_at' => 1679714985,
    'deleted_at' => 0,
  ),
  7 => 
  array (
    'id' => 80,
    'permission_name' => '任务日志',
    'parent_id' => 73,
    'level' => '73',
    'route' => '/monitor/crontab/log/:crontab_id?',
    'icon' => 'DataLine',
    'module' => 'monitor',
    'permission_mark' => 'CrontabLog',
    'component' => '/monitor/crontabLog/index',
    'redirect' => '',
    'type' => 1,
    'is_link' => 0,
    'is_full' => 0,
    'is_hidden' => 0,
    'is_affix' => 0,
    'is_keepalive' => 1,
    'sort' => 1,
    'creator_id' => 1,
    'created_at' => 1600167562,
    'updated_at' => 1679668412,
    'deleted_at' => 0,
  ),
  8 => 
  array (
    'id' => 81,
    'permission_name' => '列表',
    'parent_id' => 80,
    'level' => '73-80',
    'route' => '',
    'icon' => '',
    'module' => 'monitor',
    'permission_mark' => 'CrontabLog@index',
    'component' => '',
    'redirect' => '',
    'type' => 2,
    'is_link' => 0,
    'is_full' => 0,
    'is_hidden' => 0,
    'is_affix' => 0,
    'is_keepalive' => 1,
    'sort' => 1,
    'creator_id' => 1,
    'created_at' => 1600167574,
    'updated_at' => 1679666913,
    'deleted_at' => 0,
  ),
  9 => 
  array (
    'id' => 82,
    'permission_name' => '删除',
    'parent_id' => 80,
    'level' => '73-80',
    'route' => '',
    'icon' => '',
    'module' => 'monitor',
    'permission_mark' => 'CrontabLog@delete',
    'component' => '',
    'redirect' => '',
    'type' => 2,
    'is_link' => 0,
    'is_full' => 0,
    'is_hidden' => 0,
    'is_affix' => 0,
    'is_keepalive' => 1,
    'sort' => 1,
    'creator_id' => 1,
    'created_at' => 1600167581,
    'updated_at' => 1679666913,
    'deleted_at' => 0,
  ),
);
    }
}
